#!/usr/bin/env node
/**
 * Fetch Clerk keys from AWS Secrets Manager and write to .env
 *
 * Usage:
 *   node scripts/fetch-secrets.mjs [--stage sandbox|dev|prod]
 *
 * Requires AWS credentials with SecretsManager read access.
 */

import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const STAGE = process.argv.find((a) => a.startsWith('--stage='))?.split('=')[1] ?? 'sandbox';
const SECRET_ID = `kitchensink/${STAGE}/auth/keys`;
const ENV_FILE = resolve(import.meta.dirname, '../.env');

try {
    const raw = execSync(
        `aws secretsmanager get-secret-value --secret-id ${SECRET_ID} --query SecretString --output text`,
        { encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'] },
    );
    const { PUBLISHABLE_KEY: publishableKey } = JSON.parse(raw.trim());

    if (!publishableKey) {
        throw new Error('Missing PUBLISHABLE_KEY in secret');
    }

    const lines = [
        '# Auto-generated by scripts/fetch-secrets.mjs',
        '# Do NOT commit this file — .env is gitignored',
        '',
        '# Clerk / IDP authentication',
        `EXPO_PUBLIC_IDP_PUBLISHABLE_KEY=${publishableKey}`,
        '',
        '# API backend',
        'EXPO_PUBLIC_API_URL=https://api.commise.io',
    ];

    writeFileSync(ENV_FILE, lines.join('\n') + '\n', 'utf-8');
    console.log(`Wrote ${ENV_FILE}`);
} catch (err) {
    console.error('Failed to fetch secrets:', err.message);
    process.exit(1);
}
