/**
 * Token-to-CSS converter.
 *
 * Transforms a SystemTokens object into a CSS string containing
 * custom property declarations for both light and dark modes.
 *
 * @requirements
 * - REQ-CSS-001: Generate CSS custom properties from token definitions.
 * - REQ-CSS-002: Output light mode under `[data-system='<id>']:not(.dark)`.
 * - REQ-CSS-003: Output dark mode under `[data-system='<id>'].dark`.
 * - REQ-CSS-004: Produce output identical to hand-authored theme.css files.
 *
 * @module theme-generator/css
 */

/**
 * Maps camelCase token names to CSS custom property names.
 *
 * @type {Record<string, string>}
 */
const TOKEN_TO_CSS_PROPERTY = {
    primary: '--color-primary',
    primaryHover: '--color-primary-hover',
    primaryMuted: '--color-primary-muted',
    primaryForeground: '--color-primary-foreground',
    highlight: '--color-highlight',
    highlightHover: '--color-highlight-hover',
    highlightMuted: '--color-highlight-muted',
    highlightForeground: '--color-highlight-foreground',
    background: '--color-background',
    ring: '--color-ring',
    shadowGlow: '--shadow-glow',
};

/**
 * Generates CSS custom property declarations from a set of color mode tokens.
 *
 * @param {import('./types.d.ts').ColorModeTokens} tokens - Color mode token key-value pairs.
 * @returns {string} Indented CSS declarations.
 */
function generateDeclarations(tokens) {
    const lines = [];

    /** Token groups for visual separation in output. */
    const groups = [
        ['primary', 'primaryHover', 'primaryMuted', 'primaryForeground'],
        ['highlight', 'highlightHover', 'highlightMuted', 'highlightForeground'],
        ['background'],
        ['ring', 'shadowGlow'],
    ];

    for (let i = 0; i < groups.length; i++) {
        const group = groups[i];

        for (const tokenName of group) {
            const cssProperty = TOKEN_TO_CSS_PROPERTY[tokenName];
            const value = tokens[tokenName];

            if (cssProperty && value !== undefined) {
                lines.push(`    ${cssProperty}: ${value};`);
            }
        }

        if (i < groups.length - 1) {
            lines.push('');
        }
    }

    return lines.join('\n');
}

/**
 * Generates a complete CSS theme file from a SystemTokens definition.
 *
 * @param {import('./types.js').SystemTokens} tokens - System token definitions.
 * @returns {string} Complete CSS file content.
 */
export function generateCSS(tokens) {
    const header = [
        '/*',
        ` * ${tokens.id} — System Theme (generated)`,
        ' *',
        ' * Auto-generated by @kitchensink/theme-generator. DO NOT EDIT.',
        ` * Source: src/systems/${tokens.id}/src/public/tokens.ts`,
        ' *',
        ' * Sparse overlay: only overrides tokens that differ from the default theme.',
        ' */',
    ].join('\n');

    const lightBlock = [
        `/* --- Light mode overrides --- */`,
        `[data-system='${tokens.id}']:not(.dark) {`,
        generateDeclarations(tokens.light),
        '}',
    ].join('\n');

    const darkBlock = [
        `/* --- Dark mode overrides --- */`,
        `[data-system='${tokens.id}'].dark {`,
        generateDeclarations(tokens.dark),
        '}',
    ].join('\n');

    return `${header}\n\n${lightBlock}\n\n${darkBlock}\n`;
}
