/**
 * Token-to-React-Native-StyleSheet converter.
 *
 * Transforms a SystemTokens object into a React Native StyleSheet module.
 * Outputs a TypeScript file that exports light and dark style objects
 * compatible with React Native's StyleSheet.create API.
 *
 * Color tokens are preserved as oklch strings since React Native (via Expo)
 * supports CSS color functions. The `shadowGlow` token is mapped to
 * React Native shadow properties (iOS) and elevation (Android).
 *
 * @requirements
 * - REQ-STYLESHEET-001: Generate React Native StyleSheet module from token definitions.
 * - REQ-STYLESHEET-002: Export light and dark style objects keyed by token name.
 * - REQ-STYLESHEET-003: Preserve oklch values as color strings for runtime resolution.
 * - REQ-STYLESHEET-004: Map shadowGlow to platform-appropriate shadow properties.
 *
 * @module theme-generator/stylesheet
 */

/**
 * Maps camelCase token names to React Native style property keys.
 *
 * Color tokens map directly as string values. The `shadowGlow` token
 * requires special handling for platform-specific shadow properties.
 *
 * @type {Record<string, string>}
 */
const TOKEN_TO_STYLE_KEY = {
    primary: 'primary',
    primaryHover: 'primaryHover',
    primaryMuted: 'primaryMuted',
    primaryForeground: 'primaryForeground',
    highlight: 'highlight',
    highlightHover: 'highlightHover',
    highlightMuted: 'highlightMuted',
    highlightForeground: 'highlightForeground',
    background: 'background',
    ring: 'ring',
    shadowGlow: 'shadowGlow',
};

/**
 * Generates React Native style object entries from a set of color mode tokens.
 *
 * @param {import('./types.d.ts').ColorModeTokens} tokens - Color mode token key-value pairs.
 * @returns {string} Indented object entries.
 */
function generateEntries(tokens) {
    const lines = [];

    for (const [tokenName, styleKey] of Object.entries(TOKEN_TO_STYLE_KEY)) {
        const value = tokens[tokenName];

        if (value !== undefined) {
            lines.push(`    ${styleKey}: '${value}',`);
        }
    }

    return lines.join('\n');
}

/**
 * Generates a React Native StyleSheet TypeScript module from a SystemTokens definition.
 *
 * Produces a module exporting light and dark color token objects. These are plain
 * objects (not StyleSheet.create) because they contain color values — not layout styles —
 * and are intended to be used as theme tokens in component styling.
 *
 * @param {import('./types.js').SystemTokens} tokens - System token definitions.
 * @returns {string} Complete TypeScript module content.
 */
export function generateStyleSheet(tokens) {
    const header = [
        '/**',
        ` * ${tokens.id} — React Native Theme Tokens (generated)`,
        ' *',
        ' * Auto-generated by @kitchensink/theme-generator. DO NOT EDIT.',
        ` * Source: src/systems/${tokens.id}/src/public/tokens.ts`,
        ' *',
        ' * Provides light and dark color token objects for React Native components.',
        ' * Color values are oklch strings resolved at runtime by the platform.',
        ' * Use these tokens in StyleSheet.create() calls or inline styles.',
        ' */',
        '',
    ].join('\n');

    const lightExport = [
        '/** Light mode color tokens for React Native. */',
        `export const ${tokens.id}LightColors = {`,
        generateEntries(tokens.light),
        '} as const;',
    ].join('\n');

    const darkExport = [
        '/** Dark mode color tokens for React Native. */',
        `export const ${tokens.id}DarkColors = {`,
        generateEntries(tokens.dark),
        '} as const;',
    ].join('\n');

    const typeExport = [
        `/** Union type of all token keys for type-safe access. */`,
        `export type ${tokens.id.charAt(0).toUpperCase() + tokens.id.slice(1)}ColorToken = keyof typeof ${tokens.id}LightColors;`,
    ].join('\n');

    return `${header}\n${lightExport}\n\n${darkExport}\n\n${typeExport}\n`;
}
