/**
 * Token-to-Tamagui converter.
 *
 * Transforms a SystemTokens object into a Tamagui theme partial module.
 * Outputs a TypeScript file that exports light and dark theme objects
 * compatible with Tamagui's createTheme API.
 *
 * @requirements
 * - REQ-TAMAGUI-001: Generate Tamagui theme partial from token definitions.
 * - REQ-TAMAGUI-002: Export light and dark theme objects keyed by token name.
 * - REQ-TAMAGUI-003: Preserve oklch values as string tokens for runtime resolution.
 *
 * @module theme-generator/tamagui
 */

/**
 * Maps camelCase token names to Tamagui theme keys.
 *
 * Tamagui theme keys follow a flat camelCase convention.
 *
 * @type {Record<string, string>}
 */
const TOKEN_TO_TAMAGUI_KEY = {
    primary: 'primary',
    primaryHover: 'primaryHover',
    primaryMuted: 'primaryMuted',
    primaryForeground: 'primaryForeground',
    highlight: 'highlight',
    highlightHover: 'highlightHover',
    highlightMuted: 'highlightMuted',
    highlightForeground: 'highlightForeground',
    background: 'background',
    ring: 'ring',
    shadowGlow: 'shadowGlow',
};

/**
 * Generates Tamagui theme key-value entries from a set of color mode tokens.
 *
 * @param {import('./types.d.ts').ColorModeTokens} tokens - Color mode token key-value pairs.
 * @returns {string} Indented object entries.
 */
function generateEntries(tokens) {
    const lines = [];

    for (const [tokenName, tamaguiKey] of Object.entries(TOKEN_TO_TAMAGUI_KEY)) {
        const value = tokens[tokenName];

        if (value !== undefined) {
            lines.push(`    ${tamaguiKey}: '${value}',`);
        }
    }

    return lines.join('\n');
}

/**
 * Generates a Tamagui theme partial TypeScript module from a SystemTokens definition.
 *
 * @param {import('./types.js').SystemTokens} tokens - System token definitions.
 * @returns {string} Complete TypeScript module content.
 */
export function generateTamagui(tokens) {
    const header = [
        '/**',
        ` * ${tokens.id} — Tamagui Theme Partial (generated)`,
        ' *',
        ' * Auto-generated by @kitchensink/theme-generator. DO NOT EDIT.',
        ` * Source: src/systems/${tokens.id}/src/public/tokens.ts`,
        ' *',
        ' * Provides light and dark theme objects for Tamagui createTheme.',
        ' * Color values are oklch strings resolved at runtime by the platform.',
        ' */',
        '',
    ].join('\n');

    const lightExport = [
        '/** Light mode theme tokens for Tamagui. */',
        `export const ${tokens.id}Light = {`,
        generateEntries(tokens.light),
        '} as const;',
    ].join('\n');

    const darkExport = [
        '/** Dark mode theme tokens for Tamagui. */',
        `export const ${tokens.id}Dark = {`,
        generateEntries(tokens.dark),
        '} as const;',
    ].join('\n');

    return `${header}\n${lightExport}\n\n${darkExport}\n`;
}
